### ISSUE TITLE
Error when I try to run it

### ISSUE THREAD

**Issue by EdKeith** [alexherbo2/bulk#4]
I installed it as directed and it gave a few warnings, but said it was successful, but when I try to run it I get the following error:

bulk edit
/Users/edkeith/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- bulk (LoadError)
	from /Users/edkeith/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/edkeith/.rvm/gems/ruby-2.3.4/gems/bulk-1526921030/bin/bulk:3:in `<top (required)>'
	from /Users/edkeith/.rvm/gems/ruby-2.3.4/bin/bulk:23:in `load'
	from /Users/edkeith/.rvm/gems/ruby-2.3.4/bin/bulk:23:in `<main>'
	from /Users/edkeith/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/edkeith/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'

I am running Mac OS X 10.13.4 and ruby version 2.3.4p301 and gem 2.6.14.

**Comment by alexherbo2** [comment]
Looks like Bulk is not in your load path.

What is the output of `$:` in IRB?

**Comment by EdKeith** [comment]
2.3.4 :001 > $:
 => ["/Users/edkeith/.rvm/gems/ruby-2.3.4@global/gems/did_you_mean-1.0.0/lib", "/Users/edkeith/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0", "/Users/edkeith/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/x86_64-darwin16", "/Users/edkeith/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby", "/Users/edkeith/.rvm/rubies/ruby-2.3.4/lib/ruby/vendor_ruby/2.3.0", "/Users/edkeith/.rvm/rubies/ruby-2.3.4/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin16", "/Users/edkeith/.rvm/rubies/ruby-2.3.4/lib/ruby/vendor_ruby", "/Users/edkeith/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0", "/Users/edkeith/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/x86_64-darwin16"]

**Comment by alexherbo2** [comment]
Hey.

Sorry for the delay.  I don’t have the solution for you right now, but as a quick fix and the time being, you can add [Bulk] (the [lib/] directory) to your `RUBYLIB` environment variable, so that the library gets loaded.

[Bulk]: https://github.com/alexherbo2/bulk
[lib/]: https://github.com/alexherbo2/bulk/tree/master/lib

**Comment by EdKeith** [comment]
Thank you that fixed it.
